-- Patient-level sickle cell history. Repeated clinical events may be
-- normalized into dedicated tables in a later version.

CREATE TABLE IF NOT EXISTS llx_cabinetmed_patient_drepano (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  fk_patient integer NOT NULL,
  suivi smallint DEFAULT 0,
  alert_general smallint DEFAULT 0,
  profil_hb_patient varchar(32),
  date_confirmation date,
  reference_confirmation varchar(255),
  note_identification text,
  consanguinite varchar(16),
  profil_hb_pere varchar(32),
  profil_hb_mere varchar(32),
  rang_fratrie integer,
  taille_fratrie integer,
  cas_fratrie varchar(16),
  nombre_cas_fratrie integer,
  note_cas_fratrie text,
  troubles_alimentaires text,
  activite_professionnelle text,
  vaccination_pev_date date,
  vaccination_antityphique_statut varchar(20),
  vaccination_antityphique_date date,
  vaccination_antityphique_note text,
  vaccination_pneumocoque_statut varchar(20),
  vaccination_pneumocoque_date date,
  vaccination_pneumocoque_note text,
  vaccination_meningocoque_statut varchar(20),
  vaccination_meningocoque_date date,
  vaccination_meningocoque_note text,
  vaccination_autre_libelle varchar(255),
  vaccination_autre_statut varchar(20),
  vaccination_autre_date date,
  vaccination_autre_note text,
  cvo_12_mois integer,
  hospitalisations_12_mois integer,
  complications_aigues text,
  complications_chroniques text,
  antecedents_medicochirurgicaux text,
  transfusion_statut varchar(16),
  derniere_transfusion_date date,
  nombre_transfusions integer,
  note_transfusions text,
  datec datetime,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_cabinetmed_patient_drepano (fk_patient)
) ENGINE=innodb;
